### ISSUE TITLE
dvizh\cart\widgets\ChangeOptions

### ISSUE THREAD

**Issue by mixartemev** [dvizh/yii2-cart#4]
Объясните пожалуйста смысл этого виджета, для чего он нужен и если можно, показать пример.
Заполнил везде все дополнительные поля какие смог, но виджет всеравно ничего не отображает.

**Comment by pistol88** [comment]
Виджет выводит опции для их выбора перед тем, как положить товар в корзину. Например, есть кроссовки. Данный виджет позволяет выбрать, белые кроссовки хочет покупатель или синие. Пример работы - http://demo4.dvizh.net/
Чтобы виджет вывел данные, для товара нужно "собрать" модификации на основе опций.
Чтобы опция вывелась в конструкторе модификации, нужно добавить ее в "фильтрах и опциях".
