### ISSUE TITLE
user_id dosen't have default value

### ISSUE THREAD

**Issue by gobsek** [dvizh/yii2-cart#8]
Здравствуйте. В общем, то ошибка эта возникает при добавлении модели в корзину, если юзер не залогинен. Или если будет виджет:
`<?=ElementsList::widget(['type' => ElementsList::TYPE_DROPDOWN]);?>`
- и еще в нем не срабатывает дропдаун пока не нажмешь на кнопку добавления товара, т.е. если в корзине что-то есть - она не открывается пока не добавишь еще что-то(при пустой корзине открывается надпись, что она пуста).
- если не удаляем последний товар, а уменьшаем его кол-во в 0 то в виджете остается строка товара. Может быть запретить 0?

**Comment by halumein** [comment]
добавил миграцию для дэфолтного значения. не нужно лепить разные issue'ы в одну.
